//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.ManageWeb.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLMS_Entities_Connection : DbContext
    {
        public BLMS_Entities_Connection()
            : base("name=BLMS_Entities_Connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CS_Consultant> CS_Consultant { get; set; }
        public virtual DbSet<NickNameLibrary> NickNameLibrary { get; set; }
        public virtual DbSet<UserCarIntegralRecord> UserCarIntegralRecord { get; set; }
    }
}
