//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.ManageWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_Consultant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public string Photo { get; set; }
        public string Tel { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Age { get; set; }
        public string Title { get; set; }
    }
}
