//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.ManageWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NickNameLibrary
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public Nullable<int> IsUse { get; set; }
    }
}
