//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.ManageWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCarIntegralRecord
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string CarCategory { get; set; }
        public string VIN { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
