//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.FrontWeb.Models.BBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBSComment
    {
        public int Id { get; set; }
        public Nullable<int> GuestBookId { get; set; }
        public string MemberId { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> C_Time { get; set; }
    
        public virtual BBSGuestBook BBSGuestBook { get; set; }
        public virtual BBSMember BBSMember { get; set; }
    }
}
