//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.FrontWeb.Models.BBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBSColumns
    {
        public BBSColumns()
        {
            this.BBSGuestBook = new HashSet<BBSGuestBook>();
        }
    
        public int Id { get; set; }
        public string Column_Name { get; set; }
        public string Info { get; set; }
        public string ImageSrc { get; set; }
    
        public virtual ICollection<BBSGuestBook> BBSGuestBook { get; set; }
    }
}
