//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.FrontWeb.Models.BBS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBSEntities : DbContext
    {
        public BBSEntities()
            : base("name=BBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BBSColumns> BBSColumns { get; set; }
        public virtual DbSet<BBSComment> BBSComment { get; set; }
        public virtual DbSet<BBSGuestBook> BBSGuestBook { get; set; }
        public virtual DbSet<BBSMember> BBSMember { get; set; }
    }
}
