//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcyber.BLMS.FrontWeb.Models.BBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBSMember
    {
        public BBSMember()
        {
            this.BBSComment = new HashSet<BBSComment>();
            this.BBSGuestBook = new HashSet<BBSGuestBook>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Power { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Head { get; set; }
        public string SetAtt { get; set; }
    
        public virtual ICollection<BBSComment> BBSComment { get; set; }
        public virtual ICollection<BBSGuestBook> BBSGuestBook { get; set; }
    }
}
